version: "3.7"

services:
    alice:
        image: jlesage/firefox
        container_name: alice
        restart: always
        volumes:
            - /dev/shm:/dev/shm
        ports:
            - "5800:5800"
        networks:
            - mitm
    bob:
       image: httpd:latest
       container_name: bob
       restart: always
       ports:
            - "8080:80"
       volumes: 
            - ./bob_files:/usr/local/apache2/htdocs
       networks:
            - mitm
    
    eve:
        privileged: true
        build: .
        container_name: eve
        volumes:
            - ./eve_files:/home/lunaticyber/Scrivania/sniff
        sysctls:
            # Necessary for transparent mode for mitmproxy
            - net.ipv4.ip_forward=1
            - net.ipv6.conf.all.forwarding=1
            - net.ipv4.conf.all.send_redirects=0
        networks:
            - mitm

networks:
    mitm:
